language: java
jdk:
    - oraclejdk8

before_install:
    - pip install --user codecov
script:
    - "./gradlew clean"
    - "./gradlew check"
    - "./gradlew jacocTestReport"
after_success:
    - codecov
