language: java
jdk:
    - oraclejdk8

notifications:
  email:
    recipients: 
      - hjalti15@ru.is
      - gunnarbb15@ru.is
      - armann15@ru.is
                           
    on_success: never
    on_failure: always